server:
  port:8992
spring:
  application:
    name: fxTrade2
  datasource:
    url: jdbc:postgresql://localhost:5432/fxtrade2
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  main:
    debug: true

coinGecko:
  api:
    url: https://api.coingecko.com/api/v3